# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Firebase
    url: firebase/
    weight: 20
  - name: Experiment Template
    url: exptemplate/
    weight: 25
  - name: MPLib.js
    url: mplibjs/
    weight: 30
  - name: Documentation
    url: docs/
    weight: 80
  - name: Blog
    url: blog/
    weight: 85
  - name: Examples
    url: examples/
    weight: 90
  - name: Community
    url: community/
    weight: 95

sidebar:
  - identifier: more
    name: Still need help?
    params:
      type: separator
    weight: 1
  - identifier: community
    name: "Community"
    pageRef: "/community"
    weight: 2
  - identifier: hugoDocs
    name: "Hugo Docs ↗"
    url: "https://docs.hugoblox.com"
    weight: 3
